spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service_db
    username: identity_service_user
    password: ${IDENTITY_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8081

jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  access-token-expiration: 900