package com.edusphere.identity.securityaudit.enums;

public enum SecurityAuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    PASSWORD_CHANGE,
    USER_CREATE,
    USER_STATUS_CHANGE,
    ROUTINE_ROLE_ASSIGN,
    ROUTINE_ROLE_REMOVE,
    ROLE_ASSIGNMENT_REQUEST_CREATE,
    ROLE_ASSIGNMENT_REQUEST_CANCEL,
    ROLE_ASSIGNMENT_DECISION,
    ROLE_ASSIGNMENT_FINAL_ASSIGN,
    ROLE_REMOVAL_REQUEST_CREATE,
    ROLE_REMOVAL_REQUEST_CANCEL,
    ROLE_REMOVAL_DECISION,
    ROLE_REMOVAL_FINAL_REMOVE
}
