CREATE TABLE permissions (
     id BIGSERIAL PRIMARY KEY,
     code VARCHAR(100) NOT NULL,
     description VARCHAR(500) NOT NULL,
     owning_service VARCHAR(100) NOT NULL,
     sensitive BOOLEAN NOT NULL DEFAULT FALSE,
     active BOOLEAN NOT NULL DEFAULT TRUE,
     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CONSTRAINT uk_permissions_code UNIQUE (code)
);