CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

   organization_id BIGINT NOT NULL,
   username VARCHAR(100) NOT NULL,
   password_hash VARCHAR(255) NOT NULL,

   first_name VARCHAR(100) NOT NULL,
   middle_name VARCHAR(100),
   last_name VARCHAR(100),

   email VARCHAR(150),
   phone VARCHAR(20),

   status VARCHAR(30) NOT NULL DEFAULT 'PENDING_ACTIVATION',

   failed_login_attempts INTEGER NOT NULL DEFAULT 0,
   locked_until TIMESTAMP WITH TIME ZONE,
   last_login_at TIMESTAMP WITH TIME ZONE,

   created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT uk_users_organization_username
       UNIQUE (organization_id, username),

   CONSTRAINT chk_users_failed_login_attempts
       CHECK (failed_login_attempts >= 0)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,

    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
);

CREATE INDEX idx_users_email
    ON users(email);

CREATE INDEX idx_users_phone
    ON users(phone);

CREATE INDEX idx_user_roles_role
    ON user_roles(role);