ALTER TABLE schools
    ALTER COLUMN status TYPE VARCHAR(30);

ALTER TABLE schools
    ALTER COLUMN status SET DEFAULT 'PENDING_PROVISIONING';

ALTER TABLE schools
    DROP CONSTRAINT chk_school_status;

ALTER TABLE schools
    ADD CONSTRAINT chk_school_status
        CHECK (status IN (
            'PENDING_PROVISIONING',
            'ACTIVE',
            'PROVISIONING_FAILED',
            'INACTIVE'
        ));

CREATE TABLE school_provisioning
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id            BIGINT                   NOT NULL,
    authority_name       VARCHAR(150)             NOT NULL,
    authority_username   VARCHAR(100)             NOT NULL,
    authority_email      VARCHAR(150)             NOT NULL,
    authority_phone      VARCHAR(20)              NOT NULL,
    status               VARCHAR(30)              NOT NULL DEFAULT 'PENDING',
    attempt_count        INTEGER                  NOT NULL DEFAULT 0,
    last_error_summary   VARCHAR(500),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version              BIGINT,

    CONSTRAINT fk_school_provisioning_school
        FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT uk_school_provisioning_school
        UNIQUE (school_id),
    CONSTRAINT chk_school_provisioning_status
        CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED'))
);
